"""
Seed script: Syngenta Bangladesh Limited Official Catalog (Effective 26 July 2026).
Populates/updates all 117 Syngenta products with exact packaging formulas, multipliers, and prices.
"""

import asyncio
from decimal import Decimal
from sqlalchemy import select
from app.database import async_session_maker
from app.models.product import Product
from app.constants.units import normalize_unit

BN_BRAND_MAP = {
    "Virtako 40 WG": "ভার্টাকো ৪০ ডব্লিউজি",
    "Plenum 50 WG": "প্লেনাম ৫০ ডব্লিউজি",
    "Shobicron 425 EC": "শোবিক্রন ৪২৫ ইসি",
    "Incipio 20SC": "ইনসিপিও ২০এসসি",
    "Karate 2.5 EC": "কারাতে ২.৫ ইসি",
    "Proclaim 5SG": "প্রোক্লেইম ৫এসজি",
    "Pegasus 50 SC": "পেগাসাস ৫০ এসসি",
    "Voliam Flexi 300 SC": "ভলিয়াম ফ্লেক্সি ৩০০ এসসি",
    "Actara 25 WG": "একতারা ২৫ ডব্লিউজি",
    "Denim Fit 50 WG": "ডেনিম ফিট ৫০ ডব্লিউজি",
    "Cruiser 70 WS": "ক্রুজার ৭০ ডব্লিউএস",
    "Fortenza 60 FS": "ফরটেনজা ৬০ এফএস",
    "Wallace 55EC": "ওয়ালেস ৫৫ইসি",
    "Minecto Xtra": "মিনেক্টো এক্সট্রা",
    "Alika 24.7 ZC": "আলিকা ২৪.৭ জেডসি",
    "Fasaltap 50 SP": "ফসলট্যাপ ৫০ এসপি",
    "Ficor 50 SC": "ফিকর ৫০ এসসি",
    "Vestoria 20 WG": "ভেস্টোরিয়া ২০ ডব্লিউজি",
    "Atresia 10DC": "এট্রেসিয়া ১০ডিসি",
    "Virtako Combo": "ভার্টাকো কম্বো",
    "Vertimec 018 EC": "ভার্টিমেক ০১৮ ইসি",
    "Tilt 250 EC": "টিল্ট ২৫০ ইসি",
    "Score 250 EC": "স্কোর ২৫০ ইসি",
    "Amistar Top 325 SC": "এমিটার টপ ৩২৫ এসসি",
    "Filia 525 SE": "ফিলিয়া ৫২৫ এসই",
    "Ridomil Gold MZ 68WG": "রিডোমিল গোল্ড এমজেড ৬৮ডব্লিউজি",
    "Jazz 80 WP": "জ্যাজ ৮০ ডব্লিউপি",
    "Revus 250 SC": "রেভাস ২৫০ এসসি",
    "Miravis Duo 20SC": "মিরাভিস ডুও ২০এসসি",
    "Armure 30EC": "আরমুর ৩০ইসি",
    "Carial Flex 43WG": "ক্যারিয়াল ফ্লেক্স ৪৩ডব্লিউজি",
    "Thiovit 80 WG": "থিওভিট ৮০ ডব্লিউজি",
    "Cultar": "কাল্টার",
    "Silika 80 WG": "সিলিকা ৮০ ডব্লিউজি",
    "Caliber 50 WP": "ক্যালিবার ৫০ ডব্লিউপি",
    "Bounty 36WP": "বাউন্টি ৩৬ডব্লিউপি",
    "Cozy 45WP": "কোজি ৪৫ডব্লিউপি",
    "Rifit 500 EC": "রিফিট ৫০০ ইসি",
    "Rifit Plus 37 EW": "রিফিট প্লাস ৩৭ ইডব্লিউ",
    "Logran 75WG": "লগ্রান ৭৫ডব্লিউজি",
    "Laser 10 WP": "লেজার ১০ ডব্লিউপি",
    "Calaris Xtra 27.5 SC": "ক্যালেরিস এক্সট্রা ২৭.৫ এসসি",
    "Fusilade Max 12.5 EC": "ফিউসিলেড ম্যাক্স ১২.৫ ইসি",
    "Fasal Up 48SL": "ফসল আপ ৪৮এসএল",
    "Gayle 18WP": "গেল ১৮ডব্লিউপি",
    "Clavengo 20 SL": "ক্লাভেঙ্গো ২০ এসএল",
    "Protozim": "প্রোটোজিম",
    "Prime Plus": "প্রাইম প্লাস",
    "Bingo": "বিঙ্গো",
    "Bingo-SAC": "বিঙ্গো-স্যাক",
    "Magma": "ম্যাগমা",
    "Magma-SAC": "ম্যাগমা-স্যাক",
    "Grozin": "গ্রোজিন",
    "Lanirat": "ল্যানিরেট",
    "PJ-16 Sprayer": "পিজে-১৬ স্প্রেয়ার",
    "PJB 16 Sprayer": "পিজেবি ১৬ স্প্রেয়ার",
    "XP-16": "এক্সপি-১৬",
}

SYNGENTA_PRODUCTS = [
    # Insecticides
    {
        "agi_code": "72598",
        "brand_name": "Virtako 40 WG",
        "unit_size": "10 gm",
        "pack_size": "4 x 10 x 10 gm",
        "carton_multiplier": 40,
        "category": "Insecticide",
        "unit": "PACK",
        "mrp": "180.00",
        "retailer_carton": "6428.57",
        "retailer_pack": "160.71",
        "distributor_carton": "6122.45",
        "distributor_pack": "153.06",
    },
    {
        "agi_code": "72597",
        "brand_name": "Virtako 40 WG",
        "unit_size": "30 gm",
        "pack_size": "2 x 10 x 30 gm",
        "carton_multiplier": 20,
        "category": "Insecticide",
        "unit": "PACK",
        "mrp": "530.00",
        "retailer_carton": "9464.29",
        "retailer_pack": "473.21",
        "distributor_carton": "9013.61",
        "distributor_pack": "450.68",
    },
    {
        "agi_code": "64213",
        "brand_name": "Plenum 50 WG",
        "unit_size": "50 gm",
        "pack_size": "4 X 10 X 50 gm",
        "carton_multiplier": 40,
        "category": "Insecticide",
        "unit": "PACK",
        "mrp": "300.00",
        "retailer_carton": "10700.00",
        "retailer_pack": "267.50",
        "distributor_carton": "10190.00",
        "distributor_pack": "254.75",
    },
    {
        "agi_code": "66917",
        "brand_name": "Plenum 50 WG",
        "unit_size": "100 gm",
        "pack_size": "2 X 10 x 100 gm",
        "carton_multiplier": 20,
        "category": "Insecticide",
        "unit": "PACK",
        "mrp": "580.00",
        "retailer_carton": "10356.00",
        "retailer_pack": "517.80",
        "distributor_carton": "9862.00",
        "distributor_pack": "493.10",
    },
    {
        "agi_code": "29568",
        "brand_name": "Shobicron 425 EC",
        "unit_size": "50 ml",
        "pack_size": "20 x 50 ml",
        "carton_multiplier": 20,
        "category": "Insecticide",
        "unit": "BOTTLE",
        "mrp": "130.00",
        "retailer_carton": "2320.00",
        "retailer_pack": "116.00",
        "distributor_carton": "2210.00",
        "distributor_pack": "110.50",
    },
    {
        "agi_code": "42123",
        "brand_name": "Shobicron 425 EC",
        "unit_size": "100 ml",
        "pack_size": "20 x 100 ml",
        "carton_multiplier": 20,
        "category": "Insecticide",
        "unit": "BOTTLE",
        "mrp": "240.00",
        "retailer_carton": "4285.00",
        "retailer_pack": "214.25",
        "distributor_carton": "4080.00",
        "distributor_pack": "204.00",
    },
    {
        "agi_code": "29570",
        "brand_name": "Shobicron 425 EC",
        "unit_size": "500 ml",
        "pack_size": "10 x 500 ml",
        "carton_multiplier": 10,
        "category": "Insecticide",
        "unit": "BOTTLE",
        "mrp": "1100.00",
        "retailer_carton": "9820.00",
        "retailer_pack": "982.00",
        "distributor_carton": "9350.00",
        "distributor_pack": "935.00",
    },
    {
        "agi_code": "87913",
        "brand_name": "Incipio 20SC",
        "unit_size": "40 ml",
        "pack_size": "25X40 ml",
        "carton_multiplier": 25,
        "category": "Insecticide",
        "unit": "BOTTLE",
        "mrp": "500.00",
        "retailer_carton": "11160.75",
        "retailer_pack": "446.43",
        "distributor_carton": "10629.25",
        "distributor_pack": "425.17",
    },
    {
        "agi_code": "75229",
        "brand_name": "Incipio 20SC",
        "unit_size": "100 ml",
        "pack_size": "20 x 100 ml",
        "carton_multiplier": 20,
        "category": "Insecticide",
        "unit": "BOTTLE",
        "mrp": "1200.00",
        "retailer_carton": "21428.60",
        "retailer_pack": "1071.43",
        "distributor_carton": "20408.20",
        "distributor_pack": "1020.41",
    },
    {
        "agi_code": "58896",
        "brand_name": "Karate 2.5 EC",
        "unit_size": "50 ml",
        "pack_size": "50 x 50 ml",
        "carton_multiplier": 50,
        "category": "Insecticide",
        "unit": "BOTTLE",
        "mrp": "80.00",
        "retailer_carton": "3570.00",
        "retailer_pack": "71.40",
        "distributor_carton": "3400.00",
        "distributor_pack": "68.00",
    },
    {
        "agi_code": "58890",
        "brand_name": "Karate 2.5 EC",
        "unit_size": "100 ml",
        "pack_size": "50 x 100 ml",
        "carton_multiplier": 50,
        "category": "Insecticide",
        "unit": "BOTTLE",
        "mrp": "150.00",
        "retailer_carton": "6695.00",
        "retailer_pack": "133.90",
        "distributor_carton": "6375.00",
        "distributor_pack": "127.50",
    },
    {
        "agi_code": "58886",
        "brand_name": "Karate 2.5 EC",
        "unit_size": "500 ml",
        "pack_size": "10 x 500 ml",
        "carton_multiplier": 10,
        "category": "Insecticide",
        "unit": "BOTTLE",
        "mrp": "680.00",
        "retailer_carton": "6071.00",
        "retailer_pack": "607.10",
        "distributor_carton": "5782.00",
        "distributor_pack": "578.20",
    },
    {
        "agi_code": "70887",
        "brand_name": "Proclaim 5SG",
        "unit_size": "10 gm",
        "pack_size": "4 x 10 x 10 gm",
        "carton_multiplier": 40,
        "category": "Insecticide",
        "unit": "PACK",
        "mrp": "80.00",
        "retailer_carton": "2856.00",
        "retailer_pack": "71.40",
        "distributor_carton": "2720.00",
        "distributor_pack": "68.00",
    },
    {
        "agi_code": "70897",
        "brand_name": "Proclaim 5SG",
        "unit_size": "30 gm",
        "pack_size": "2 x 10 x 30 gm",
        "carton_multiplier": 20,
        "category": "Insecticide",
        "unit": "PACK",
        "mrp": "200.00",
        "retailer_carton": "3570.00",
        "retailer_pack": "178.50",
        "distributor_carton": "3400.00",
        "distributor_pack": "170.00",
    },
    {
        "agi_code": "87199",
        "brand_name": "Proclaim 5SG",
        "unit_size": "10 gm",
        "pack_size": "4 x 12 x 10 gm",
        "carton_multiplier": 48,
        "category": "Insecticide",
        "unit": "PACK",
        "mrp": "80.00",
        "retailer_carton": "3417.60",
        "retailer_pack": "71.20",
        "distributor_carton": "3246.72",
        "distributor_pack": "67.64",
    },
    {
        "agi_code": "59214",
        "brand_name": "Pegasus 50 SC",
        "unit_size": "50 ml",
        "pack_size": "20 x 50 ml",
        "carton_multiplier": 20,
        "category": "Insecticide",
        "unit": "BOTTLE",
        "mrp": "180.00",
        "retailer_carton": "3214.00",
        "retailer_pack": "160.70",
        "distributor_carton": "3060.00",
        "distributor_pack": "153.00",
    },
    {
        "agi_code": "61124",
        "brand_name": "Pegasus 50 SC",
        "unit_size": "100 ml",
        "pack_size": "20 x 100 ml",
        "carton_multiplier": 20,
        "category": "Insecticide",
        "unit": "BOTTLE",
        "mrp": "350.00",
        "retailer_carton": "6248.00",
        "retailer_pack": "312.40",
        "distributor_carton": "5948.00",
        "distributor_pack": "297.40",
    },
    {
        "agi_code": "43978",
        "brand_name": "Voliam Flexi 300 SC",
        "unit_size": "50 ml",
        "pack_size": "20 x 50 ml",
        "carton_multiplier": 20,
        "category": "Insecticide",
        "unit": "BOTTLE",
        "mrp": "380.00",
        "retailer_carton": "6784.00",
        "retailer_pack": "339.20",
        "distributor_carton": "6460.54",
        "distributor_pack": "323.03",
    },
    {
        "agi_code": "34779",
        "brand_name": "Actara 25 WG",
        "unit_size": "5 gm",
        "pack_size": "25 x 8 x 5 gm",
        "carton_multiplier": 200,
        "category": "Insecticide",
        "unit": "PACK",
        "mrp": "60.00",
        "retailer_carton": "10710.00",
        "retailer_pack": "53.55",
        "distributor_carton": "10200.00",
        "distributor_pack": "51.00",
    },
    {
        "agi_code": "87221",
        "brand_name": "Actara 25 WG",
        "unit_size": "5 gm",
        "pack_size": "20 x 12 x 5 gm",
        "carton_multiplier": 240,
        "category": "Insecticide",
        "unit": "PACK",
        "mrp": "60.00",
        "retailer_carton": "12816.00",
        "retailer_pack": "53.40",
        "distributor_carton": "12175.20",
        "distributor_pack": "50.73",
    },
    {
        "agi_code": "87224",
        "brand_name": "Denim Fit 50 WG",
        "unit_size": "10 gm",
        "pack_size": "4 x 12 x 10 gm",
        "carton_multiplier": 48,
        "category": "Insecticide",
        "unit": "PACK",
        "mrp": "200.00",
        "retailer_carton": "8544.00",
        "retailer_pack": "178.00",
        "distributor_carton": "8116.80",
        "distributor_pack": "169.10",
    },
    {
        "agi_code": "59688",
        "brand_name": "Denim Fit 50 WG",
        "unit_size": "10 gm",
        "pack_size": "4 x 10 x 10 gm",
        "carton_multiplier": 40,
        "category": "Insecticide",
        "unit": "PACK",
        "mrp": "200.00",
        "retailer_carton": "7142.00",
        "retailer_pack": "178.55",
        "distributor_carton": "6800.00",
        "distributor_pack": "170.00",
    },
    {
        "agi_code": "63913",
        "brand_name": "Cruiser 70 WS",
        "unit_size": "20 gm",
        "pack_size": "2 X 25 X 20 gm",
        "carton_multiplier": 50,
        "category": "Insecticide",
        "unit": "PACK",
        "mrp": "150.00",
        "retailer_carton": "6695.00",
        "retailer_pack": "133.90",
        "distributor_carton": "6375.00",
        "distributor_pack": "127.50",
    },
    {
        "agi_code": "70007",
        "brand_name": "Fortenza 60 FS",
        "unit_size": "10 ml",
        "pack_size": "10 x 10 ml",
        "carton_multiplier": 10,
        "category": "Insecticide",
        "unit": "BOTTLE",
        "mrp": "300.00",
        "retailer_carton": "2678.00",
        "retailer_pack": "267.80",
        "distributor_carton": "2550.00",
        "distributor_pack": "255.00",
    },
    {
        "agi_code": "71830",
        "brand_name": "Wallace 55EC",
        "unit_size": "100 ml",
        "pack_size": "20 x 100 ml",
        "carton_multiplier": 20,
        "category": "Insecticide",
        "unit": "BOTTLE",
        "mrp": "180.00",
        "retailer_carton": "3214.00",
        "retailer_pack": "160.70",
        "distributor_carton": "3060.00",
        "distributor_pack": "153.00",
    },
    {
        "agi_code": "72524",
        "brand_name": "Wallace 55EC",
        "unit_size": "500 ml",
        "pack_size": "10 x 500 ml",
        "carton_multiplier": 10,
        "category": "Insecticide",
        "unit": "BOTTLE",
        "mrp": "800.00",
        "retailer_carton": "7142.00",
        "retailer_pack": "714.20",
        "distributor_carton": "6801.00",
        "distributor_pack": "680.10",
    },
    {
        "agi_code": "72434",
        "brand_name": "Minecto Xtra",
        "unit_size": "10 ml",
        "pack_size": "4 x 10 x 10 ml",
        "carton_multiplier": 40,
        "category": "Insecticide",
        "unit": "BOTTLE",
        "mrp": "180.00",
        "retailer_carton": "6420.00",
        "retailer_pack": "160.50",
        "distributor_carton": "6110.00",
        "distributor_pack": "152.75",
    },
    {
        "agi_code": "74275",
        "brand_name": "Minecto Xtra",
        "unit_size": "50 ml",
        "pack_size": "20 x 50 ml",
        "carton_multiplier": 20,
        "category": "Insecticide",
        "unit": "BOTTLE",
        "mrp": "700.00",
        "retailer_carton": "12500.00",
        "retailer_pack": "625.00",
        "distributor_carton": "11904.00",
        "distributor_pack": "595.20",
    },
    {
        "agi_code": "69667",
        "brand_name": "Alika 24.7 ZC",
        "unit_size": "50 ml",
        "pack_size": "20 x 50 ml",
        "carton_multiplier": 20,
        "category": "Insecticide",
        "unit": "BOTTLE",
        "mrp": "230.00",
        "retailer_carton": "4106.00",
        "retailer_pack": "205.30",
        "distributor_carton": "3910.00",
        "distributor_pack": "195.50",
    },
    {
        "agi_code": "70966",
        "brand_name": "Alika 24.7 ZC",
        "unit_size": "100 ml",
        "pack_size": "20 x 100 ml",
        "carton_multiplier": 20,
        "category": "Insecticide",
        "unit": "BOTTLE",
        "mrp": "415.00",
        "retailer_carton": "7410.00",
        "retailer_pack": "370.50",
        "distributor_carton": "7057.00",
        "distributor_pack": "352.85",
    },
    {
        "agi_code": "68508",
        "brand_name": "Fasaltap 50 SP",
        "unit_size": "100 gm",
        "pack_size": "30 x 100 gm",
        "carton_multiplier": 30,
        "category": "Insecticide",
        "unit": "PACK",
        "mrp": "250.00",
        "retailer_carton": "6696.00",
        "retailer_pack": "223.20",
        "distributor_carton": "6375.00",
        "distributor_pack": "212.50",
    },
    {
        "agi_code": "72523",
        "brand_name": "Fasaltap 50 SP",
        "unit_size": "50 gm",
        "pack_size": "40 X 50 gm",
        "carton_multiplier": 40,
        "category": "Insecticide",
        "unit": "PACK",
        "mrp": "150.00",
        "retailer_carton": "5356.00",
        "retailer_pack": "133.90",
        "distributor_carton": "5100.00",
        "distributor_pack": "127.50",
    },
    {
        "agi_code": "71014",
        "brand_name": "Ficor 50 SC",
        "unit_size": "100 ml",
        "pack_size": "20 x 100 ml",
        "carton_multiplier": 20,
        "category": "Insecticide",
        "unit": "BOTTLE",
        "mrp": "160.00",
        "retailer_carton": "2856.00",
        "retailer_pack": "142.80",
        "distributor_carton": "2720.00",
        "distributor_pack": "136.00",
    },
    {
        "agi_code": "71013",
        "brand_name": "Ficor 50 SC",
        "unit_size": "400 ml",
        "pack_size": "10 x 400 ml",
        "carton_multiplier": 10,
        "category": "Insecticide",
        "unit": "BOTTLE",
        "mrp": "560.00",
        "retailer_carton": "5000.00",
        "retailer_pack": "500.00",
        "distributor_carton": "4760.00",
        "distributor_pack": "476.00",
    },
    {
        "agi_code": "84793",
        "brand_name": "Vestoria 20 WG",
        "unit_size": "15 gm",
        "pack_size": "25X15 gm",
        "carton_multiplier": 25,
        "category": "Insecticide",
        "unit": "PACK",
        "mrp": "450.00",
        "retailer_carton": "10012.50",
        "retailer_pack": "400.50",
        "distributor_carton": "9511.88",
        "distributor_pack": "380.48",
    },
    {
        "agi_code": "84811",
        "brand_name": "Vestoria 20 WG",
        "unit_size": "50 gm",
        "pack_size": "10X50 gm",
        "carton_multiplier": 10,
        "category": "Insecticide",
        "unit": "PACK",
        "mrp": "1450.00",
        "retailer_carton": "12905.00",
        "retailer_pack": "1290.50",
        "distributor_carton": "12259.75",
        "distributor_pack": "1225.98",
    },
    {
        "agi_code": "88294",
        "brand_name": "Atresia 10DC",
        "unit_size": "50 ml",
        "pack_size": "100X50 ml",
        "carton_multiplier": 100,
        "category": "Insecticide",
        "unit": "BOTTLE",
        "mrp": "550.00",
        "retailer_carton": "48950.00",
        "retailer_pack": "489.50",
        "distributor_carton": "46502.50",
        "distributor_pack": "465.03",
    },
    {
        "agi_code": "88739",
        "brand_name": "Virtako Combo",
        "unit_size": "10 gm",
        "pack_size": "50X10 gm",
        "carton_multiplier": 50,
        "category": "Insecticide",
        "unit": "PACK",
        "mrp": "200.00",
        "retailer_carton": "8928.57",
        "retailer_pack": "178.57",
        "distributor_carton": "8503.40",
        "distributor_pack": "170.07",
    },
    {
        "agi_code": "63105",
        "brand_name": "Vertimec 018 EC",
        "unit_size": "50 ml",
        "pack_size": "20 x 50 ml",
        "carton_multiplier": 20,
        "category": "Insecticide",
        "unit": "BOTTLE",
        "mrp": "100.00",
        "retailer_carton": "1784.00",
        "retailer_pack": "89.20",
        "distributor_carton": "1698.00",
        "distributor_pack": "84.90",
    },
    {
        "agi_code": "63106",
        "brand_name": "Vertimec 018 EC",
        "unit_size": "100 ml",
        "pack_size": "20 x 100 ml",
        "carton_multiplier": 20,
        "category": "Insecticide",
        "unit": "BOTTLE",
        "mrp": "190.00",
        "retailer_carton": "3392.00",
        "retailer_pack": "169.60",
        "distributor_carton": "3230.00",
        "distributor_pack": "161.50",
    },
    {
        "agi_code": "63107",
        "brand_name": "Vertimec 018 EC",
        "unit_size": "500 ml",
        "pack_size": "10 x 500 ml",
        "carton_multiplier": 10,
        "category": "Insecticide",
        "unit": "BOTTLE",
        "mrp": "850.00",
        "retailer_carton": "7589.00",
        "retailer_pack": "758.90",
        "distributor_carton": "7226.00",
        "distributor_pack": "722.60",
    },

    # Fungicides
    {
        "agi_code": "58888",
        "brand_name": "Tilt 250 EC",
        "unit_size": "50 ml",
        "pack_size": "20 x 50 ml",
        "carton_multiplier": 20,
        "category": "Fungicide",
        "unit": "BOTTLE",
        "mrp": "180.00",
        "retailer_carton": "3214.00",
        "retailer_pack": "160.70",
        "distributor_carton": "3060.00",
        "distributor_pack": "153.00",
    },
    {
        "agi_code": "58889",
        "brand_name": "Tilt 250 EC",
        "unit_size": "100 ml",
        "pack_size": "20 x 100 ml",
        "carton_multiplier": 20,
        "category": "Fungicide",
        "unit": "BOTTLE",
        "mrp": "330.00",
        "retailer_carton": "5892.00",
        "retailer_pack": "294.60",
        "distributor_carton": "5610.00",
        "distributor_pack": "280.50",
    },
    {
        "agi_code": "58887",
        "brand_name": "Tilt 250 EC",
        "unit_size": "500 ml",
        "pack_size": "10 x 500 ml",
        "carton_multiplier": 10,
        "category": "Fungicide",
        "unit": "BOTTLE",
        "mrp": "1350.00",
        "retailer_carton": "12054.00",
        "retailer_pack": "1205.40",
        "distributor_carton": "11480.00",
        "distributor_pack": "1148.00",
    },
    {
        "agi_code": "34002",
        "brand_name": "Score 250 EC",
        "unit_size": "50 ml",
        "pack_size": "20 x 50 ml",
        "carton_multiplier": 20,
        "category": "Fungicide",
        "unit": "BOTTLE",
        "mrp": "180.00",
        "retailer_carton": "3210.00",
        "retailer_pack": "160.50",
        "distributor_carton": "3055.92",
        "distributor_pack": "152.80",
    },
    {
        "agi_code": "30593",
        "brand_name": "Score 250 EC",
        "unit_size": "100 ml",
        "pack_size": "20 x 100 ml",
        "carton_multiplier": 20,
        "category": "Fungicide",
        "unit": "BOTTLE",
        "mrp": "340.00",
        "retailer_carton": "6070.00",
        "retailer_pack": "303.50",
        "distributor_carton": "5780.46",
        "distributor_pack": "289.02",
    },
    {
        "agi_code": "34001",
        "brand_name": "Score 250 EC",
        "unit_size": "500 ml",
        "pack_size": "10 x 500 ml",
        "carton_multiplier": 10,
        "category": "Fungicide",
        "unit": "BOTTLE",
        "mrp": "1500.00",
        "retailer_carton": "13390.00",
        "retailer_pack": "1339.00",
        "distributor_carton": "12751.30",
        "distributor_pack": "1275.13",
    },
    {
        "agi_code": "88631",
        "brand_name": "Amistar Top 325 SC",
        "unit_size": "50 ml",
        "pack_size": "20 x 50 ml",
        "carton_multiplier": 20,
        "category": "Fungicide",
        "unit": "BOTTLE",
        "mrp": "230.00",
        "retailer_carton": "4107.00",
        "retailer_pack": "205.35",
        "distributor_carton": "3911.00",
        "distributor_pack": "195.55",
    },
    {
        "agi_code": "88630",
        "brand_name": "Amistar Top 325 SC",
        "unit_size": "100 ml",
        "pack_size": "20 x 100 ml",
        "carton_multiplier": 20,
        "category": "Fungicide",
        "unit": "BOTTLE",
        "mrp": "450.00",
        "retailer_carton": "8036.00",
        "retailer_pack": "401.80",
        "distributor_carton": "7653.00",
        "distributor_pack": "382.65",
    },
    {
        "agi_code": "88626",
        "brand_name": "Amistar Top 325 SC",
        "unit_size": "500 ml",
        "pack_size": "10 x 500 ml",
        "carton_multiplier": 10,
        "category": "Fungicide",
        "unit": "BOTTLE",
        "mrp": "1950.00",
        "retailer_carton": "17410.00",
        "retailer_pack": "1741.00",
        "distributor_carton": "16579.00",
        "distributor_pack": "1657.90",
    },
    {
        "agi_code": "53294",
        "brand_name": "Amistar Top 325 SC",
        "unit_size": "50 ml",
        "pack_size": "20 x 50 ml",
        "carton_multiplier": 20,
        "category": "Fungicide",
        "unit": "BOTTLE",
        "mrp": "230.00",
        "retailer_carton": "4107.00",
        "retailer_pack": "205.35",
        "distributor_carton": "3911.00",
        "distributor_pack": "195.55",
    },
    {
        "agi_code": "46652",
        "brand_name": "Amistar Top 325 SC",
        "unit_size": "100 ml",
        "pack_size": "20 x 100 ml",
        "carton_multiplier": 20,
        "category": "Fungicide",
        "unit": "BOTTLE",
        "mrp": "450.00",
        "retailer_carton": "8036.00",
        "retailer_pack": "401.80",
        "distributor_carton": "7653.00",
        "distributor_pack": "382.65",
    },
    {
        "agi_code": "51574",
        "brand_name": "Amistar Top 325 SC",
        "unit_size": "500 ml",
        "pack_size": "10 x 500 ml",
        "carton_multiplier": 10,
        "category": "Fungicide",
        "unit": "BOTTLE",
        "mrp": "1950.00",
        "retailer_carton": "17410.00",
        "retailer_pack": "1741.00",
        "distributor_carton": "16579.00",
        "distributor_pack": "1657.90",
    },
    {
        "agi_code": "55458",
        "brand_name": "Filia 525 SE",
        "unit_size": "50 ml",
        "pack_size": "20 x 50 ml",
        "carton_multiplier": 20,
        "category": "Fungicide",
        "unit": "BOTTLE",
        "mrp": "170.00",
        "retailer_carton": "3036.00",
        "retailer_pack": "151.80",
        "distributor_carton": "2891.00",
        "distributor_pack": "144.55",
    },
    {
        "agi_code": "46420",
        "brand_name": "Filia 525 SE",
        "unit_size": "100 ml",
        "pack_size": "20 x 100 ml",
        "carton_multiplier": 20,
        "category": "Fungicide",
        "unit": "BOTTLE",
        "mrp": "300.00",
        "retailer_carton": "5357.00",
        "retailer_pack": "267.85",
        "distributor_carton": "5102.00",
        "distributor_pack": "255.10",
    },
    {
        "agi_code": "57918",
        "brand_name": "Filia 525 SE",
        "unit_size": "500 ml",
        "pack_size": "10 x 500 ml",
        "carton_multiplier": 10,
        "category": "Fungicide",
        "unit": "BOTTLE",
        "mrp": "1400.00",
        "retailer_carton": "12500.00",
        "retailer_pack": "1250.00",
        "distributor_carton": "11905.00",
        "distributor_pack": "1190.50",
    },
    {
        "agi_code": "38775",
        "brand_name": "Ridomil Gold MZ 68WG",
        "unit_size": "100 gm",
        "pack_size": "30 x 100 gm",
        "carton_multiplier": 30,
        "category": "Fungicide",
        "unit": "PACK",
        "mrp": "200.00",
        "retailer_carton": "5355.00",
        "retailer_pack": "178.50",
        "distributor_carton": "5099.57",
        "distributor_pack": "169.99",
    },
    {
        "agi_code": "38776",
        "brand_name": "Ridomil Gold MZ 68WG",
        "unit_size": "0.5 kg",
        "pack_size": "10 x 0.5 kg",
        "carton_multiplier": 10,
        "category": "Fungicide",
        "unit": "PACK",
        "mrp": "950.00",
        "retailer_carton": "8481.00",
        "retailer_pack": "848.10",
        "distributor_carton": "8076.46",
        "distributor_pack": "807.65",
    },
    {
        "agi_code": "45144",
        "brand_name": "Ridomil Gold MZ 68WG",
        "unit_size": "1 kg",
        "pack_size": "10 x 1 kg",
        "carton_multiplier": 10,
        "category": "Fungicide",
        "unit": "PACK",
        "mrp": "890.00",
        "retailer_carton": "7945.00",
        "retailer_pack": "794.50",
        "distributor_carton": "7566.02",
        "distributor_pack": "756.60",
    },
    {
        "agi_code": "52537",
        "brand_name": "Jazz 80 WP",
        "unit_size": "500 gm",
        "pack_size": "10 x 500 gm",
        "carton_multiplier": 10,
        "category": "Fungicide",
        "unit": "PACK",
        "mrp": "450.00",
        "retailer_carton": "4015.00",
        "retailer_pack": "401.50",
        "distributor_carton": "3823.48",
        "distributor_pack": "382.35",
    },
    {
        "agi_code": "52539",
        "brand_name": "Jazz 80 WP",
        "unit_size": "100 gm",
        "pack_size": "30 x 100 gm",
        "carton_multiplier": 30,
        "category": "Fungicide",
        "unit": "PACK",
        "mrp": "120.00",
        "retailer_carton": "3210.00",
        "retailer_pack": "107.00",
        "distributor_carton": "3056.88",
        "distributor_pack": "101.90",
    },
    {
        "agi_code": "58513",
        "brand_name": "Revus 250 SC",
        "unit_size": "50 ml",
        "pack_size": "20 x 50 ml",
        "carton_multiplier": 20,
        "category": "Fungicide",
        "unit": "BOTTLE",
        "mrp": "250.00",
        "retailer_carton": "4464.00",
        "retailer_pack": "223.20",
        "distributor_carton": "4251.07",
        "distributor_pack": "212.55",
    },
    {
        "agi_code": "53508",
        "brand_name": "Revus 250 SC",
        "unit_size": "100 ml",
        "pack_size": "20 x 100 ml",
        "carton_multiplier": 20,
        "category": "Fungicide",
        "unit": "BOTTLE",
        "mrp": "480.00",
        "retailer_carton": "8570.00",
        "retailer_pack": "428.50",
        "distributor_carton": "8161.21",
        "distributor_pack": "408.06",
    },
    {
        "agi_code": "53924",
        "brand_name": "Revus 250 SC",
        "unit_size": "500 ml",
        "pack_size": "10 x 500 ml",
        "carton_multiplier": 10,
        "category": "Fungicide",
        "unit": "BOTTLE",
        "mrp": "2250.00",
        "retailer_carton": "20088.00",
        "retailer_pack": "2008.80",
        "distributor_carton": "19129.80",
        "distributor_pack": "1912.98",
    },
    {
        "agi_code": "80927",
        "brand_name": "Miravis Duo 20SC",
        "unit_size": "50 ml",
        "pack_size": "20 x 50 ml",
        "carton_multiplier": 20,
        "category": "Fungicide",
        "unit": "BOTTLE",
        "mrp": "450.00",
        "retailer_carton": "8000.00",
        "retailer_pack": "400.00",
        "distributor_carton": "7600.00",
        "distributor_pack": "380.00",
    },
    {
        "agi_code": "81359",
        "brand_name": "Miravis Duo 20SC",
        "unit_size": "100 ml",
        "pack_size": "20 x 100 ml",
        "carton_multiplier": 20,
        "category": "Fungicide",
        "unit": "BOTTLE",
        "mrp": "850.00",
        "retailer_carton": "15180.00",
        "retailer_pack": "759.00",
        "distributor_carton": "14456.00",
        "distributor_pack": "722.80",
    },
    {
        "agi_code": "85250",
        "brand_name": "Armure 30EC",
        "unit_size": "100 ml",
        "pack_size": "20 x 100 ml",
        "carton_multiplier": 20,
        "category": "Fungicide",
        "unit": "BOTTLE",
        "mrp": "450.00",
        "retailer_carton": "8000.00",
        "retailer_pack": "400.00",
        "distributor_carton": "7600.00",
        "distributor_pack": "380.00",
    },
    {
        "agi_code": "85803",
        "brand_name": "Carial Flex 43WG",
        "unit_size": "70 gm",
        "pack_size": "3 x 10 x 70 gm",
        "carton_multiplier": 30,
        "category": "Fungicide",
        "unit": "PACK",
        "mrp": "600.00",
        "retailer_carton": "16020.00",
        "retailer_pack": "534.00",
        "distributor_carton": "15219.00",
        "distributor_pack": "507.30",
    },
    {
        "agi_code": "16238",
        "brand_name": "Thiovit 80 WG",
        "unit_size": "0.5 kg",
        "pack_size": "10 x 0.5 kg",
        "carton_multiplier": 10,
        "category": "Fungicide",
        "unit": "PACK",
        "mrp": "200.00",
        "retailer_carton": "1785.00",
        "retailer_pack": "178.50",
        "distributor_carton": "1699.46",
        "distributor_pack": "169.95",
    },
    {
        "agi_code": "16239",
        "brand_name": "Thiovit 80 WG",
        "unit_size": "1 kg",
        "pack_size": "10 X 1 Kg",
        "carton_multiplier": 10,
        "category": "Fungicide",
        "unit": "PACK",
        "mrp": "350.00",
        "retailer_carton": "3120.00",
        "retailer_pack": "312.00",
        "distributor_carton": "2971.66",
        "distributor_pack": "297.17",
    },
    {
        "agi_code": "16240",
        "brand_name": "Thiovit 80 WG",
        "unit_size": "2 kg",
        "pack_size": "5 x 2 kg",
        "carton_multiplier": 5,
        "category": "Fungicide",
        "unit": "PACK",
        "mrp": "650.00",
        "retailer_carton": "2900.00",
        "retailer_pack": "580.00",
        "distributor_carton": "2762.11",
        "distributor_pack": "552.42",
    },
    {
        "agi_code": "92798",
        "brand_name": "Thiovit 80 WG",
        "unit_size": "1 kg",
        "pack_size": "12X1 KG",
        "carton_multiplier": 12,
        "category": "Fungicide",
        "unit": "PACK",
        "mrp": "370.00",
        "retailer_carton": "3966.00",
        "retailer_pack": "330.50",
        "distributor_carton": "3777.44",
        "distributor_pack": "314.79",
    },
    {
        "agi_code": "92795",
        "brand_name": "Thiovit 80 WG",
        "unit_size": "2 kg",
        "pack_size": "6x2 KG",
        "carton_multiplier": 6,
        "category": "Fungicide",
        "unit": "PACK",
        "mrp": "680.00",
        "retailer_carton": "3642.00",
        "retailer_pack": "607.00",
        "distributor_carton": "3468.83",
        "distributor_pack": "578.14",
    },
    {
        "agi_code": "30004",
        "brand_name": "Thiovit 80 WG",
        "unit_size": "25 kg",
        "pack_size": "25 kg",
        "carton_multiplier": 1,
        "category": "Fungicide",
        "unit": "BAG",
        "mrp": "5500.00",
        "retailer_carton": "5500.00",
        "retailer_pack": "5500.00",
        "distributor_carton": "5500.00",
        "distributor_pack": "5500.00",
    },
    {
        "agi_code": "88725",
        "brand_name": "Cultar",
        "unit_size": "500 ml",
        "pack_size": "10x500 ml",
        "carton_multiplier": 10,
        "category": "Plant Growth",
        "unit": "BOTTLE",
        "mrp": "1250.00",
        "retailer_carton": "11160.00",
        "retailer_pack": "1116.00",
        "distributor_carton": "10630.00",
        "distributor_pack": "1063.00",
    },
    {
        "agi_code": "47314",
        "brand_name": "Silika 80 WG",
        "unit_size": "0.5 kg",
        "pack_size": "10 X 0.5 kg",
        "carton_multiplier": 10,
        "category": "Fungicide",
        "unit": "PACK",
        "mrp": "140.00",
        "retailer_carton": "1250.00",
        "retailer_pack": "125.00",
        "distributor_carton": "1190.00",
        "distributor_pack": "119.00",
    },
    {
        "agi_code": "58337",
        "brand_name": "Silika 80 WG",
        "unit_size": "1 kg",
        "pack_size": "10 x 1 kg",
        "carton_multiplier": 10,
        "category": "Fungicide",
        "unit": "PACK",
        "mrp": "350.00",
        "retailer_carton": "3125.00",
        "retailer_pack": "312.50",
        "distributor_carton": "2975.39",
        "distributor_pack": "297.54",
    },
    {
        "agi_code": "63914",
        "brand_name": "Silika 80 WG",
        "unit_size": "2 kg",
        "pack_size": "5 x 2 kg",
        "carton_multiplier": 5,
        "category": "Fungicide",
        "unit": "PACK",
        "mrp": "670.00",
        "retailer_carton": "2990.00",
        "retailer_pack": "598.00",
        "distributor_carton": "2846.85",
        "distributor_pack": "569.37",
    },
    {
        "agi_code": "68507",
        "brand_name": "Caliber 50 WP",
        "unit_size": "100 gm",
        "pack_size": "30 x 100 gm",
        "carton_multiplier": 30,
        "category": "Fungicide",
        "unit": "PACK",
        "mrp": "140.00",
        "retailer_carton": "3750.00",
        "retailer_pack": "125.00",
        "distributor_carton": "3570.00",
        "distributor_pack": "119.00",
    },
    {
        "agi_code": "70283",
        "brand_name": "Caliber 50 WP",
        "unit_size": "500 gm",
        "pack_size": "10 x 500 gm",
        "carton_multiplier": 10,
        "category": "Fungicide",
        "unit": "PACK",
        "mrp": "630.00",
        "retailer_carton": "5625.00",
        "retailer_pack": "562.50",
        "distributor_carton": "5356.00",
        "distributor_pack": "535.60",
    },
    {
        "agi_code": "71016",
        "brand_name": "Bounty 36WP",
        "unit_size": "100 gm",
        "pack_size": "30 x 100 gm",
        "carton_multiplier": 30,
        "category": "Fungicide",
        "unit": "PACK",
        "mrp": "120.00",
        "retailer_carton": "3213.00",
        "retailer_pack": "107.10",
        "distributor_carton": "3060.00",
        "distributor_pack": "102.00",
    },
    {
        "agi_code": "71017",
        "brand_name": "Bounty 36WP",
        "unit_size": "500 gm",
        "pack_size": "10 x 500 gm",
        "carton_multiplier": 10,
        "category": "Fungicide",
        "unit": "PACK",
        "mrp": "550.00",
        "retailer_carton": "4910.00",
        "retailer_pack": "491.00",
        "distributor_carton": "4676.00",
        "distributor_pack": "467.60",
    },
    {
        "agi_code": "70182",
        "brand_name": "Cozy 45WP",
        "unit_size": "100 gm",
        "pack_size": "30 x 100 gm",
        "carton_multiplier": 30,
        "category": "Fungicide",
        "unit": "PACK",
        "mrp": "170.00",
        "retailer_carton": "4551.00",
        "retailer_pack": "151.70",
        "distributor_carton": "4332.00",
        "distributor_pack": "144.40",
    },

    # Herbicides
    {
        "agi_code": "35348",
        "brand_name": "Rifit 500 EC",
        "unit_size": "100 ml",
        "pack_size": "20 x 100 ml",
        "carton_multiplier": 20,
        "category": "Herbicide",
        "unit": "BOTTLE",
        "mrp": "140.00",
        "retailer_carton": "2500.00",
        "retailer_pack": "125.00",
        "distributor_carton": "2380.00",
        "distributor_pack": "119.00",
    },
    {
        "agi_code": "30688",
        "brand_name": "Rifit 500 EC",
        "unit_size": "500 ml",
        "pack_size": "10 x 500 ml",
        "carton_multiplier": 10,
        "category": "Herbicide",
        "unit": "BOTTLE",
        "mrp": "540.00",
        "retailer_carton": "4821.00",
        "retailer_pack": "482.10",
        "distributor_carton": "4591.00",
        "distributor_pack": "459.10",
    },
    {
        "agi_code": "67637",
        "brand_name": "Rifit Plus 37 EW",
        "unit_size": "250 ml",
        "pack_size": "20 x 250 ml",
        "carton_multiplier": 20,
        "category": "Herbicide",
        "unit": "BOTTLE",
        "mrp": "330.00",
        "retailer_carton": "5890.50",
        "retailer_pack": "294.53",
        "distributor_carton": "5610.00",
        "distributor_pack": "280.50",
    },
    {
        "agi_code": "78917",
        "brand_name": "Rifit Plus 37 EW",
        "unit_size": "165 ml",
        "pack_size": "20 x 165 ml",
        "carton_multiplier": 20,
        "category": "Herbicide",
        "unit": "BOTTLE",
        "mrp": "230.00",
        "retailer_carton": "4105.50",
        "retailer_pack": "205.28",
        "distributor_carton": "3910.00",
        "distributor_pack": "195.50",
    },
    {
        "agi_code": "66559",
        "brand_name": "Logran 75WG",
        "unit_size": "3 gm",
        "pack_size": "10 x 10 x 3 gm",
        "carton_multiplier": 100,
        "category": "Herbicide",
        "unit": "PACK",
        "mrp": "80.00",
        "retailer_carton": "7140.00",
        "retailer_pack": "71.40",
        "distributor_carton": "6800.00",
        "distributor_pack": "68.00",
    },
    {
        "agi_code": "43868",
        "brand_name": "Laser 10 WP",
        "unit_size": "25 gm",
        "pack_size": "4 x 30 x 25 gm",
        "carton_multiplier": 120,
        "category": "Herbicide",
        "unit": "PACK",
        "mrp": "50.00",
        "retailer_carton": "5340.00",
        "retailer_pack": "44.50",
        "distributor_carton": "5073.00",
        "distributor_pack": "42.28",
    },
    {
        "agi_code": "75062",
        "brand_name": "Calaris Xtra 27.5 SC",
        "unit_size": "500 ml",
        "pack_size": "20 x 500 ml",
        "carton_multiplier": 20,
        "category": "Herbicide",
        "unit": "BOTTLE",
        "mrp": "580.00",
        "retailer_carton": "10355.63",
        "retailer_pack": "517.78",
        "distributor_carton": "9860.00",
        "distributor_pack": "493.00",
    },
    {
        "agi_code": "59997",
        "brand_name": "Fusilade Max 12.5 EC",
        "unit_size": "100 ml",
        "pack_size": "20 x 100 ml",
        "carton_multiplier": 20,
        "category": "Herbicide",
        "unit": "BOTTLE",
        "mrp": "250.00",
        "retailer_carton": "4464.00",
        "retailer_pack": "223.20",
        "distributor_carton": "4250.00",
        "distributor_pack": "212.50",
    },
    {
        "agi_code": "82888",
        "brand_name": "Fasal Up 48SL",
        "unit_size": "1 Lt",
        "pack_size": "10 x 1 lt",
        "carton_multiplier": 10,
        "category": "Herbicide",
        "unit": "BOTTLE",
        "mrp": "790.00",
        "retailer_carton": "7050.00",
        "retailer_pack": "705.00",
        "distributor_carton": "6714.00",
        "distributor_pack": "671.40",
    },
    {
        "agi_code": "82898",
        "brand_name": "Fasal Up 48SL",
        "unit_size": "500 ml",
        "pack_size": "10 x 500ml",
        "carton_multiplier": 10,
        "category": "Herbicide",
        "unit": "BOTTLE",
        "mrp": "430.00",
        "retailer_carton": "3837.75",
        "retailer_pack": "383.78",
        "distributor_carton": "3655.00",
        "distributor_pack": "365.50",
    },
    {
        "agi_code": "69037",
        "brand_name": "Gayle 18WP",
        "unit_size": "100 gm",
        "pack_size": "30 x 100 gm",
        "carton_multiplier": 30,
        "category": "Herbicide",
        "unit": "PACK",
        "mrp": "90.00",
        "retailer_carton": "2403.00",
        "retailer_pack": "80.30",
        "distributor_carton": "2282.85",
        "distributor_pack": "76.40",
    },
    {
        "agi_code": "80490",
        "brand_name": "Clavengo 20 SL",
        "unit_size": "200 ml",
        "pack_size": "50 x 200 ml",
        "carton_multiplier": 50,
        "category": "Herbicide",
        "unit": "BOTTLE",
        "mrp": "270.00",
        "retailer_carton": "12050.00",
        "retailer_pack": "241.00",
        "distributor_carton": "11475.00",
        "distributor_pack": "229.50",
    },

    # Plant Nutrition & Growth
    {
        "agi_code": "59703",
        "brand_name": "Protozim",
        "unit_size": "50 ml",
        "pack_size": "40 x 50 ml",
        "carton_multiplier": 40,
        "category": "Plant Growth",
        "unit": "BOTTLE",
        "mrp": "170.00",
        "retailer_carton": "6069.00",
        "retailer_pack": "151.73",
        "distributor_carton": "5780.00",
        "distributor_pack": "144.50",
    },
    {
        "agi_code": "59704",
        "brand_name": "Protozim",
        "unit_size": "100 ml",
        "pack_size": "20 x 100 ml",
        "carton_multiplier": 20,
        "category": "Plant Growth",
        "unit": "BOTTLE",
        "mrp": "300.00",
        "retailer_carton": "5355.00",
        "retailer_pack": "267.75",
        "distributor_carton": "5100.00",
        "distributor_pack": "255.00",
    },
    {
        "agi_code": "59769",
        "brand_name": "Protozim",
        "unit_size": "500 ml",
        "pack_size": "10 x 500 ml",
        "carton_multiplier": 10,
        "category": "Plant Growth",
        "unit": "BOTTLE",
        "mrp": "1400.00",
        "retailer_carton": "12495.00",
        "retailer_pack": "1249.50",
        "distributor_carton": "11900.00",
        "distributor_pack": "1190.00",
    },
    {
        "agi_code": "84781",
        "brand_name": "Prime Plus",
        "unit_size": "1 Lt",
        "pack_size": "12 x 1 Lt",
        "carton_multiplier": 12,
        "category": "Plant Growth",
        "unit": "BOTTLE",
        "mrp": "3500.00",
        "retailer_carton": "37485.00",
        "retailer_pack": "3123.75",
        "distributor_carton": "35685.72",
        "distributor_pack": "2973.81",
    },
    {
        "agi_code": "63728",
        "brand_name": "Bingo",
        "unit_size": "100 gm",
        "pack_size": "30 x 100 gm",
        "carton_multiplier": 30,
        "category": "Fertilizer",
        "unit": "PACK",
        "mrp": "90.00",
        "retailer_carton": "2408.40",
        "retailer_pack": "80.28",
        "distributor_carton": "2292.30",
        "distributor_pack": "76.41",
    },
    {
        "agi_code": "63730",
        "brand_name": "Bingo",
        "unit_size": "0.5 kg",
        "pack_size": "20 x 0.5 kg",
        "carton_multiplier": 20,
        "category": "Fertilizer",
        "unit": "PACK",
        "mrp": "370.00",
        "retailer_carton": "6606.65",
        "retailer_pack": "330.33",
        "distributor_carton": "6291.72",
        "distributor_pack": "314.59",
    },
    {
        "agi_code": "87269",
        "brand_name": "Bingo-SAC",
        "unit_size": "100 gm",
        "pack_size": "30 x 100 gm",
        "carton_multiplier": 30,
        "category": "Fertilizer",
        "unit": "PACK",
        "mrp": "90.00",
        "retailer_carton": "2408.40",
        "retailer_pack": "80.28",
        "distributor_carton": "2292.30",
        "distributor_pack": "76.41",
    },
    {
        "agi_code": "87848",
        "brand_name": "Bingo-SAC",
        "unit_size": "0.5 kg",
        "pack_size": "20 x 0.5 kg",
        "carton_multiplier": 20,
        "category": "Fertilizer",
        "unit": "PACK",
        "mrp": "370.00",
        "retailer_carton": "6606.65",
        "retailer_pack": "330.33",
        "distributor_carton": "6291.72",
        "distributor_pack": "314.59",
    },
    {
        "agi_code": "90521",
        "brand_name": "Magma-SAC",
        "unit_size": "1 kg",
        "pack_size": "10 x 1 kg",
        "carton_multiplier": 10,
        "category": "Fertilizer",
        "unit": "PACK",
        "mrp": "160.00",
        "retailer_carton": "1428.00",
        "retailer_pack": "142.80",
        "distributor_carton": "1360.00",
        "distributor_pack": "136.00",
    },
    {
        "agi_code": "90556",
        "brand_name": "Magma-SAC",
        "unit_size": "2 kg",
        "pack_size": "5 x 2 kg",
        "carton_multiplier": 5,
        "category": "Fertilizer",
        "unit": "PACK",
        "mrp": "300.00",
        "retailer_carton": "1338.75",
        "retailer_pack": "267.75",
        "distributor_carton": "1275.00",
        "distributor_pack": "255.00",
    },
    {
        "agi_code": "63731",
        "brand_name": "Magma",
        "unit_size": "1 kg",
        "pack_size": "10 x 1 kg",
        "carton_multiplier": 10,
        "category": "Fertilizer",
        "unit": "PACK",
        "mrp": "160.00",
        "retailer_carton": "1428.00",
        "retailer_pack": "142.80",
        "distributor_carton": "1360.00",
        "distributor_pack": "136.00",
    },
    {
        "agi_code": "55296",
        "brand_name": "Magma",
        "unit_size": "2 kg",
        "pack_size": "5 x 2 kg",
        "carton_multiplier": 5,
        "category": "Fertilizer",
        "unit": "PACK",
        "mrp": "300.00",
        "retailer_carton": "1339.00",
        "retailer_pack": "267.80",
        "distributor_carton": "1275.00",
        "distributor_pack": "255.00",
    },
    {
        "agi_code": "35440",
        "brand_name": "Grozin",
        "unit_size": "1 kg",
        "pack_size": "10 x 1 Kg",
        "carton_multiplier": 10,
        "category": "Fertilizer",
        "unit": "PACK",
        "mrp": "330.00",
        "retailer_carton": "2945.25",
        "retailer_pack": "294.53",
        "distributor_carton": "2803.88",
        "distributor_pack": "280.39",
    },
    {
        "agi_code": "92493",
        "brand_name": "Grozin",
        "unit_size": "1 kg",
        "pack_size": "10 x 1 Kg",
        "carton_multiplier": 10,
        "category": "Fertilizer",
        "unit": "PACK",
        "mrp": "330.00",
        "retailer_carton": "2945.25",
        "retailer_pack": "294.53",
        "distributor_carton": "2803.88",
        "distributor_pack": "280.39",
    },
    {
        "agi_code": "93175",
        "brand_name": "Grozin",
        "unit_size": "1 kg",
        "pack_size": "10 x 1 Kg",
        "carton_multiplier": 10,
        "category": "Fertilizer",
        "unit": "PACK",
        "mrp": "330.00",
        "retailer_carton": "2945.25",
        "retailer_pack": "294.53",
        "distributor_carton": "2803.88",
        "distributor_pack": "280.39",
    },
    {
        "agi_code": "81636",
        "brand_name": "Grozin",
        "unit_size": "2 kg",
        "pack_size": "5 x 2 kg",
        "carton_multiplier": 5,
        "category": "Fertilizer",
        "unit": "PACK",
        "mrp": "630.00",
        "retailer_carton": "2811.38",
        "retailer_pack": "562.28",
        "distributor_carton": "2676.43",
        "distributor_pack": "535.29",
    },
    {
        "agi_code": "56655",
        "brand_name": "Grozin",
        "unit_size": "2 kg",
        "pack_size": "5 x 2 kg",
        "carton_multiplier": 5,
        "category": "Fertilizer",
        "unit": "PACK",
        "mrp": "630.00",
        "retailer_carton": "2811.38",
        "retailer_pack": "562.28",
        "distributor_carton": "2676.43",
        "distributor_pack": "535.29",
    },
    {
        "agi_code": "93171",
        "brand_name": "Grozin",
        "unit_size": "2 kg",
        "pack_size": "5 x 2 kg",
        "carton_multiplier": 5,
        "category": "Fertilizer",
        "unit": "PACK",
        "mrp": "630.00",
        "retailer_carton": "2811.38",
        "retailer_pack": "562.28",
        "distributor_carton": "2676.43",
        "distributor_pack": "535.29",
    },

    # Rodenticide
    {
        "agi_code": "35723",
        "brand_name": "Lanirat",
        "unit_size": "100 gm",
        "pack_size": "40 x 100 gm",
        "carton_multiplier": 40,
        "category": "Rodenticide",
        "unit": "PACK",
        "mrp": "60.00",
        "retailer_carton": "2140.80",
        "retailer_pack": "53.52",
        "distributor_carton": "2035.20",
        "distributor_pack": "50.88",
    },

    # Equipment
    {
        "agi_code": "202255",
        "brand_name": "PJ-16 Sprayer",
        "unit_size": "1 Unit",
        "pack_size": "1 UNIT",
        "carton_multiplier": 1,
        "category": "Equipment",
        "unit": "UNIT",
        "mrp": "8000.00",
        "retailer_carton": "7195.00",
        "retailer_pack": "7195.00",
        "distributor_carton": "6787.00",
        "distributor_pack": "6787.00",
    },
    {
        "agi_code": "4132143",
        "brand_name": "PJB 16 Sprayer",
        "unit_size": "1 Unit",
        "pack_size": "1 UNIT",
        "carton_multiplier": 1,
        "category": "Equipment",
        "unit": "UNIT",
        "mrp": "13000.00",
        "retailer_carton": "12264.00",
        "retailer_pack": "12264.00",
        "distributor_carton": "11907.00",
        "distributor_pack": "11907.00",
    },
    {
        "agi_code": "4035253",
        "brand_name": "XP-16",
        "unit_size": "1 Unit",
        "pack_size": "1 UNIT",
        "carton_multiplier": 1,
        "category": "Equipment",
        "unit": "UNIT",
        "mrp": "4500.00",
        "retailer_carton": "4045.00",
        "retailer_pack": "4045.00",
        "distributor_carton": "3816.00",
        "distributor_pack": "3816.00",
    },
]


async def seed_syngenta_catalog() -> dict:
    """
    Idempotently seeds all 117 Syngenta products into the database.
    """
    created_count = 0
    updated_count = 0

    async with async_session_maker() as session:
        for item in SYNGENTA_PRODUCTS:
            code = item["agi_code"]
            brand = item["brand_name"]
            unit_s = item["unit_size"]

            # Compute standardized English and Bengali names
            if unit_s.lower() in brand.lower() or "unit" in unit_s.lower():
                name_en = brand
            else:
                name_en = f"{brand} ({unit_s})"

            bn_base = BN_BRAND_MAP.get(brand, brand)
            if unit_s.lower() in brand.lower() or "unit" in unit_s.lower():
                name_bn = bn_base
            else:
                name_bn = f"{bn_base} ({unit_s})"

            mrp = Decimal(item["mrp"])
            ret_pack = Decimal(item["retailer_pack"])
            ret_ctn = Decimal(item["retailer_carton"]) if item["retailer_carton"] else None
            dist_pack = Decimal(item["distributor_pack"]) if item["distributor_pack"] else None
            dist_ctn = Decimal(item["distributor_carton"]) if item["distributor_carton"] else None
            multiplier = Decimal(str(item["carton_multiplier"]))

            stmt = select(Product).where(Product.product_code == code)
            result = await session.execute(stmt)
            existing = result.scalar_one_or_none()

            if existing:
                existing.name_en = name_en
                existing.name_bn = name_bn
                existing.company_name = "Syngenta Bangladesh Limited"
                existing.category = item["category"]
                existing.base_unit = normalize_unit(item["unit"])
                existing.pack_size = item["pack_size"]
                existing.unit_size = unit_s
                existing.carton_multiplier = multiplier
                existing.standard_retail_price = mrp
                existing.standard_wholesale_price = ret_pack
                existing.buying_price = dist_pack
                existing.carton_wholesale_price = ret_ctn
                existing.carton_buying_price = dist_ctn
                updated_count += 1
            else:
                new_product = Product(
                    product_code=code,
                    name_en=name_en,
                    name_bn=name_bn,
                    company_name="Syngenta Bangladesh Limited",
                    category=item["category"],
                    base_unit=normalize_unit(item["unit"]),
                    pack_size=item["pack_size"],
                    unit_size=unit_s,
                    carton_multiplier=multiplier,
                    default_barcode=code,
                    standard_retail_price=mrp,
                    standard_wholesale_price=ret_pack,
                    buying_price=dist_pack,
                    carton_wholesale_price=ret_ctn,
                    carton_buying_price=dist_ctn,
                    min_stock_alert=5,
                )
                session.add(new_product)
                created_count += 1

        await session.commit()

    return {
        "status": "success",
        "total_catalog_items": len(SYNGENTA_PRODUCTS),
        "created": created_count,
        "updated": updated_count,
    }


if __name__ == "__main__":
    res = asyncio.run(seed_syngenta_catalog())
    print(f"Seed completed successfully: {res}")
