-- ============================================================================
-- V1__init_schema.sql
-- Al-Amin POS & Inventory Management System - Squashed Baseline
--
-- This baseline is intended for a dropped/recreated database. It represents the
-- current final system state without historical migration steps.
-- ============================================================================

CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT DEFAULT 0 NOT NULL,
    product_code VARCHAR(50) NOT NULL UNIQUE,
    name_en VARCHAR(255) NOT NULL,
    name_bn VARCHAR(255) NOT NULL,
    company_name VARCHAR(150) DEFAULT 'Agro Chem',
    category VARCHAR(100) NOT NULL,
    base_unit VARCHAR(30) NOT NULL,
    carton_multiplier NUMERIC(10, 3) DEFAULT 1.0,
    default_barcode VARCHAR(100),
    standard_retail_price NUMERIC(12, 2) NOT NULL,
    standard_wholesale_price NUMERIC(12, 2),
    buying_price NUMERIC(12, 2),
    min_stock_alert INT DEFAULT 5,
    image_path VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE inventory_lot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT DEFAULT 0 NOT NULL,
    product_id BIGINT NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    lot_number VARCHAR(50) NOT NULL,
    entry_date DATE NOT NULL,
    expiry_date DATE NOT NULL,
    purchase_cost NUMERIC(12, 2) NOT NULL,
    lot_retail_price NUMERIC(12, 2) NOT NULL,
    lot_wholesale_price NUMERIC(12, 2) NOT NULL,
    barcode VARCHAR(100) NOT NULL UNIQUE,
    supplier_name VARCHAR(150),
    challan_no VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE stock_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT DEFAULT 0 NOT NULL,
    lot_id BIGINT NOT NULL REFERENCES inventory_lot(id) ON DELETE CASCADE,
    location VARCHAR(20) NOT NULL DEFAULT 'DOKAN',
    quantity NUMERIC(12, 3) NOT NULL DEFAULT 0,
    CONSTRAINT uq_lot_location UNIQUE (lot_id, location),
    CONSTRAINT chk_stock_inventory_quantity_non_negative CHECK (quantity >= 0)
);

CREATE TABLE customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT DEFAULT 0 NOT NULL,
    name VARCHAR(200) NOT NULL,
    father_name VARCHAR(150),
    business_name VARCHAR(200),
    phone VARCHAR(50) NOT NULL,
    whatsapp_number VARCHAR(50),
    email VARCHAR(100),
    village_address VARCHAR(255),
    customer_type VARCHAR(30) NOT NULL,
    credit_limit NUMERIC(12, 2) DEFAULT 0,
    current_due NUMERIC(12, 2) NOT NULL DEFAULT 0,
    mfs_type VARCHAR(30),
    mfs_number VARCHAR(50),
    bank_name VARCHAR(100),
    bank_branch VARCHAR(100),
    bank_account_no VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE customer_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customer(id) ON DELETE CASCADE,
    transaction_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    transaction_type VARCHAR(50) NOT NULL,
    debit NUMERIC(12, 2) DEFAULT 0,
    credit NUMERIC(12, 2) DEFAULT 0,
    balance_after NUMERIC(12, 2) NOT NULL,
    money_receipt_no VARCHAR(50),
    sale_id BIGINT,
    notes TEXT
);

CREATE TABLE sale (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT DEFAULT 0 NOT NULL,
    invoice_no VARCHAR(50) NOT NULL UNIQUE,
    sale_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    customer_id BIGINT REFERENCES customer(id),
    sale_mode VARCHAR(20) NOT NULL,
    subtotal NUMERIC(12, 2) NOT NULL,
    discount NUMERIC(12, 2) DEFAULT 0,
    round_off NUMERIC(12, 2) DEFAULT 0,
    total_amount NUMERIC(12, 2) NOT NULL,
    payment_method VARCHAR(30) NOT NULL DEFAULT 'CASH',
    cash_paid NUMERIC(12, 2) DEFAULT 0,
    cash_tendered NUMERIC(12, 2) DEFAULT 0,
    change_amount NUMERIC(12, 2) DEFAULT 0,
    digital_paid NUMERIC(12, 2) DEFAULT 0,
    digital_medium VARCHAR(30),
    digital_trx_id VARCHAR(100),
    due_amount NUMERIC(12, 2) DEFAULT 0,
    cashier_name VARCHAR(100)
);

CREATE TABLE sale_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL REFERENCES sale(id) ON DELETE CASCADE,
    lot_id BIGINT NOT NULL REFERENCES inventory_lot(id),
    total_quantity NUMERIC(12, 3) NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    unit_cost NUMERIC(12, 2) NOT NULL,
    subtotal NUMERIC(12, 2) NOT NULL
);

CREATE TABLE sale_return (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_no VARCHAR(50) NOT NULL UNIQUE,
    original_sale_id BIGINT REFERENCES sale(id),
    customer_id BIGINT REFERENCES customer(id),
    return_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_refund_amount NUMERIC(12, 2) NOT NULL,
    refund_type VARCHAR(30) NOT NULL,
    reason TEXT
);

CREATE TABLE sale_return_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_return_id BIGINT NOT NULL REFERENCES sale_return(id) ON DELETE CASCADE,
    lot_id BIGINT NOT NULL REFERENCES inventory_lot(id),
    quantity NUMERIC(12, 3) NOT NULL,
    refund_price NUMERIC(12, 2) NOT NULL,
    is_damaged BOOLEAN DEFAULT FALSE,
    restock_location VARCHAR(20) NOT NULL DEFAULT 'DOKAN'
);

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT DEFAULT 0 NOT NULL,
    username VARCHAR(60) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    full_name VARCHAR(150),
    role VARCHAR(30) NOT NULL,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMP,
    CONSTRAINT uq_app_user_username UNIQUE (username)
);

CREATE TABLE system_config (
    config_key VARCHAR(100) PRIMARY KEY,
    config_value VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE idempotency_record (
    id VARCHAR(64) PRIMARY KEY,
    status VARCHAR(20) NOT NULL,
    response_code INT,
    response_body TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE invoice_number_seq START WITH 1001 INCREMENT BY 1;
CREATE SEQUENCE return_number_seq START WITH 1001 INCREMENT BY 1;

CREATE INDEX idx_inventory_lot_product ON inventory_lot(product_id);
CREATE INDEX idx_inventory_lot_expiry ON inventory_lot(expiry_date);
CREATE INDEX idx_stock_inventory_lot ON stock_inventory(lot_id);
CREATE INDEX idx_stock_inv_lot_loc ON stock_inventory(lot_id, location);
CREATE INDEX idx_customer_phone ON customer(phone);
CREATE INDEX idx_customer_ledger_customer ON customer_ledger(customer_id);
CREATE INDEX idx_customer_ledger_sale ON customer_ledger(sale_id);
CREATE INDEX idx_customer_ledger_cust_date ON customer_ledger(customer_id, transaction_date);
CREATE INDEX idx_sale_customer ON sale(customer_id);
CREATE INDEX idx_sale_invoice ON sale(invoice_no);
CREATE INDEX idx_sale_date ON sale(sale_date DESC);
CREATE INDEX idx_sale_mode_date ON sale(sale_mode, sale_date DESC);
CREATE INDEX idx_sale_payment_method ON sale(payment_method);
CREATE INDEX idx_sale_item_sale ON sale_item(sale_id);
CREATE INDEX idx_sale_item_lot ON sale_item(lot_id);
CREATE INDEX idx_sale_return_sale ON sale_return(original_sale_id);
CREATE INDEX idx_sale_return_customer ON sale_return(customer_id);
CREATE INDEX idx_sale_return_date ON sale_return(return_date DESC);
CREATE INDEX idx_sale_return_item_return ON sale_return_item(sale_return_id);
CREATE INDEX idx_sale_return_item_lot ON sale_return_item(lot_id);

INSERT INTO product (
    product_code, name_en, name_bn, company_name, category,
    base_unit, carton_multiplier, default_barcode,
    standard_retail_price, standard_wholesale_price, buying_price,
    min_stock_alert, image_path
) VALUES
('SYN-AMI-TOP', 'Amistar Top 325 SC', 'Amistar Top 325 SC', 'Agro Chem', 'Fungicide', 'Bottle', 20.000, 'SYN-AMI-202601', 650.00, 580.00, 520.00, 5, '/images/products/amistar_top.png'),
('SYN-VIR-40WG', 'Virtako 40 WG', 'Virtako 40 WG', 'Agro Chem', 'Insecticide', 'Packet', 50.000, 'SYN-VIR-40WG', 350.00, 310.00, 275.00, 10, '/images/products/virtako.png'),
('SYN-REF-500', 'Refit 500 EC', 'Refit 500 EC', 'Agro Chem', 'Herbicide', 'Bottle', 20.000, 'SYN-REF-500', 480.00, 420.00, 380.00, 5, '/images/products/refit.png'),
('SYN-ISA-BIO', 'Isabion', 'Isabion', 'Agro Chem', 'Bio-stimulant', 'Bottle', 20.000, 'SYN-ISA-BIO', 320.00, 280.00, 250.00, 5, '/images/products/isabion.png'),
('SYN-KAR-25EC', 'Karate 2.5 EC', 'Karate 2.5 EC', 'Agro Chem', 'Insecticide', 'Bottle', 20.000, 'SYN-KAR-25EC', 260.00, 230.00, 200.00, 5, '/images/products/karate.png'),
('SYN-SCO-250EC', 'Score 250 EC', 'Score 250 EC', 'Agro Chem', 'Fungicide', 'Bottle', 20.000, 'SYN-SCO-250EC', 420.00, 380.00, 320.00, 5, '/images/products/score.png');

INSERT INTO inventory_lot (
    product_id, lot_number, entry_date, expiry_date,
    purchase_cost, lot_retail_price, lot_wholesale_price,
    barcode, supplier_name, challan_no
) VALUES
((SELECT id FROM product WHERE product_code = 'SYN-AMI-TOP'), 'DEFAULT', '2026-05-15', '2030-12-31', 500.00, 650.00, 580.00, 'SYN-AMI-202502', NULL, NULL),
((SELECT id FROM product WHERE product_code = 'SYN-AMI-TOP'), 'AMI-NEW-202609', '2026-09-19', '2031-12-31', 590.00, 720.00, 680.00, 'SYN-AMI-NEW-202609', 'Agro Chemical Ltd', 'CH-SYN-202609'),
((SELECT id FROM product WHERE product_code = 'SYN-VIR-40WG'), 'DEFAULT', '2026-08-10', '2030-12-31', 275.00, 350.00, 310.00, 'SYN-VIR-202601', NULL, NULL),
((SELECT id FROM product WHERE product_code = 'SYN-REF-500'), 'DEFAULT', '2026-08-15', '2030-12-31', 380.00, 480.00, 420.00, 'SYN-REF-202601', NULL, NULL),
((SELECT id FROM product WHERE product_code = 'SYN-ISA-BIO'), 'DEFAULT', '2026-08-20', '2030-12-31', 250.00, 320.00, 280.00, 'SYN-ISA-202601', NULL, NULL),
((SELECT id FROM product WHERE product_code = 'SYN-KAR-25EC'), 'DEFAULT', '2026-08-25', '2030-12-31', 200.00, 260.00, 230.00, 'SYN-KAR-202601', NULL, NULL),
((SELECT id FROM product WHERE product_code = 'SYN-SCO-250EC'), 'DEFAULT', '2026-09-01', '2030-12-31', 320.00, 420.00, 380.00, 'SYN-SCO-250EC', NULL, NULL);

INSERT INTO stock_inventory (lot_id, location, quantity) VALUES
((SELECT id FROM inventory_lot WHERE barcode = 'SYN-AMI-202502'), 'DOKAN', 40.000),
((SELECT id FROM inventory_lot WHERE barcode = 'SYN-AMI-NEW-202609'), 'DOKAN', 50.000),
((SELECT id FROM inventory_lot WHERE barcode = 'SYN-VIR-202601'), 'DOKAN', 25.000),
((SELECT id FROM inventory_lot WHERE barcode = 'SYN-REF-202601'), 'DOKAN', 10.000),
((SELECT id FROM inventory_lot WHERE barcode = 'SYN-ISA-202601'), 'DOKAN', 8.000),
((SELECT id FROM inventory_lot WHERE barcode = 'SYN-KAR-202601'), 'DOKAN', 12.000),
((SELECT id FROM inventory_lot WHERE barcode = 'SYN-SCO-250EC'), 'DOKAN', 90.000);

INSERT INTO customer (
    name, father_name, business_name, phone, whatsapp_number,
    email, village_address, customer_type, credit_limit, current_due,
    mfs_type, mfs_number, bank_name, bank_branch, bank_account_no
) VALUES
('মো: রফিকুল ইসলাম', 'মো: আজহার আলী', 'মেসার্স মদিনা ট্রেডার্স', '01711000001', '01711000001', 'modina.traders@example.com', 'চকবাজার, শেরপুর সদর, শেরপুর', 'WHOLESALE', 100000.00, 15000.00, 'BKASH', '01711000001', 'Islami Bank Bangladesh PLC', 'Sherpur Branch', '20501234567890'),
('করিম মিয়া', 'আব্দুল করিম', NULL, '01811000002', '01811000002', NULL, 'চর শেরপুর, শেরপুর', 'RETAIL', 0.00, 0.00, 'NAGAD', '01811000002', NULL, NULL, NULL);

INSERT INTO customer_ledger (
    customer_id, transaction_date, transaction_type,
    debit, credit, balance_after, money_receipt_no, sale_id, notes
) VALUES
((SELECT id FROM customer WHERE phone = '01711000001'), TIMESTAMP '2026-09-01 09:00:00', 'INVOICE_BILL', 15000.00, 0.00, 15000.00, NULL, NULL, 'Opening balance prior to system migration');

-- owner / owner123
INSERT INTO app_user (username, password_hash, full_name, role, active)
VALUES ('owner', '$2b$10$ZX1S0b8lqGKqdqa7Vd8iq.AQJ.BfPpp/DQMu7nezZMWnTDYajvZ.W', 'Shop Owner', 'ROLE_OWNER', TRUE);
