-- ============================================================================
-- V1__init_schema.sql
-- Al-Amin POS & Inventory Management System - Initial Database Schema
--
-- Compatibility: Dual-compatible with H2 2.x+ and PostgreSQL 10+
-- BUSINESS DECISION: Standard ANSI SQL Identity columns (BIGINT GENERATED BY DEFAULT AS IDENTITY)
-- ensure dual portability across H2 (development/embedded) and PostgreSQL (production).
-- ============================================================================

-- 1. Product Master Catalog
CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code VARCHAR(50) NOT NULL UNIQUE,
    name_en VARCHAR(255) NOT NULL,
    name_bn VARCHAR(255) NOT NULL,
    company_name VARCHAR(150) DEFAULT 'Agro Chem',
    category VARCHAR(100) NOT NULL,
    base_unit VARCHAR(30) NOT NULL,
    carton_multiplier NUMERIC(10, 3) DEFAULT 1.0,
    default_barcode VARCHAR(100),
    standard_retail_price NUMERIC(12, 2) NOT NULL,
    standard_wholesale_price NUMERIC(12, 2) NOT NULL,
    min_stock_alert INT DEFAULT 5,
    image_path VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Inventory Lots (Batches) with Cost & Expiry Tracking
CREATE TABLE inventory_lot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    lot_number VARCHAR(50) NOT NULL,
    entry_date DATE NOT NULL,
    expiry_date DATE NOT NULL,
    purchase_cost NUMERIC(12, 2) NOT NULL,
    lot_retail_price NUMERIC(12, 2) NOT NULL,
    lot_wholesale_price NUMERIC(12, 2) NOT NULL,
    barcode VARCHAR(100) NOT NULL UNIQUE,
    supplier_name VARCHAR(150),
    challan_no VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Stock Inventory by Location per Lot
-- BUSINESS DECISION: Quantities are stored exclusively in base units using NUMERIC(12, 3)
-- with a composite unique key (lot_id, location) to prevent multi-location inventory drift.
CREATE TABLE stock_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_id BIGINT NOT NULL REFERENCES inventory_lot(id) ON DELETE CASCADE,
    location VARCHAR(20) NOT NULL, -- 'DOKAN' or 'GODOWN'
    quantity NUMERIC(12, 3) NOT NULL DEFAULT 0,
    CONSTRAINT uq_lot_location UNIQUE (lot_id, location)
);

-- 4. Godown Movement Audit Log (Date-wise Entry & Exit)
CREATE TABLE godown_movement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_id BIGINT NOT NULL REFERENCES inventory_lot(id),
    movement_type VARCHAR(50) NOT NULL, -- 'PURCHASE_ENTRY', 'TRANSFER_TO_DOKAN', 'DIRECT_WHOLESALE_DISPATCH', 'DAMAGE_EXIT', 'RETURN_ENTRY'
    quantity NUMERIC(12, 3) NOT NULL,
    movement_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reference_no VARCHAR(100),
    remarks TEXT
);

-- 5. Customer Profile (Wholesale Dealers & Retail Accounts)
CREATE TABLE customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    father_name VARCHAR(150),
    business_name VARCHAR(200),
    phone VARCHAR(50) NOT NULL,
    whatsapp_number VARCHAR(50),
    email VARCHAR(100),
    village_address VARCHAR(255),
    customer_type VARCHAR(30) NOT NULL, -- 'WHOLESALE' or 'RETAIL'
    credit_limit NUMERIC(12, 2) DEFAULT 0,
    current_due NUMERIC(12, 2) NOT NULL DEFAULT 0,
    mfs_type VARCHAR(30),
    mfs_number VARCHAR(50),
    bank_name VARCHAR(100),
    bank_branch VARCHAR(100),
    bank_account_no VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. Customer Due Ledger (Bakir Khata)
-- BUSINESS DECISION: customer_ledger.sale_id is left unconstrained by a foreign key
-- to support non-sale ledger entries (opening balances, direct cash receipts) without synthetic sale records.
CREATE TABLE customer_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customer(id) ON DELETE CASCADE,
    transaction_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    transaction_type VARCHAR(50) NOT NULL, -- 'INVOICE_BILL', 'CASH_PAYMENT', 'RETURN_CREDIT'
    debit NUMERIC(12, 2) DEFAULT 0,
    credit NUMERIC(12, 2) DEFAULT 0,
    balance_after NUMERIC(12, 2) NOT NULL,
    money_receipt_no VARCHAR(50),
    sale_id BIGINT,
    notes TEXT
);

-- 7. Sales Invoices
CREATE TABLE sale (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no VARCHAR(50) NOT NULL UNIQUE,
    sale_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    customer_id BIGINT REFERENCES customer(id),
    sale_mode VARCHAR(20) NOT NULL, -- 'RETAIL' or 'WHOLESALE'
    subtotal NUMERIC(12, 2) NOT NULL,
    discount NUMERIC(12, 2) DEFAULT 0,
    round_off NUMERIC(12, 2) DEFAULT 0,
    total_amount NUMERIC(12, 2) NOT NULL,
    payment_method VARCHAR(30) NOT NULL DEFAULT 'CASH', -- 'CASH', 'BKASH', 'NAGAD', 'BANK_TRANSFER', 'DUE', 'SPLIT'
    cash_paid NUMERIC(12, 2) DEFAULT 0,
    digital_paid NUMERIC(12, 2) DEFAULT 0,
    digital_medium VARCHAR(30),
    digital_trx_id VARCHAR(100),
    due_amount NUMERIC(12, 2) DEFAULT 0,
    cashier_name VARCHAR(100)
);

-- 8. Sale Items with Split Fulfillment & Cost Snapshot
-- BUSINESS DECISION: sale_item stores a frozen snapshot of unit_cost at transaction time
-- to guarantee accurate historical gross profit calculations.
CREATE TABLE sale_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL REFERENCES sale(id) ON DELETE CASCADE,
    lot_id BIGINT NOT NULL REFERENCES inventory_lot(id),
    total_quantity NUMERIC(12, 3) NOT NULL,
    dokan_quantity NUMERIC(12, 3) NOT NULL DEFAULT 0,
    godown_quantity NUMERIC(12, 3) NOT NULL DEFAULT 0,
    unit_price NUMERIC(12, 2) NOT NULL,
    unit_cost NUMERIC(12, 2) NOT NULL,
    subtotal NUMERIC(12, 2) NOT NULL
);

-- 9. Sales Return
-- BUSINESS DECISION: sale_return.original_sale_id is nullable to support direct
-- receipt-less returns common in rural agricultural dealerships.
CREATE TABLE sale_return (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_no VARCHAR(50) NOT NULL UNIQUE,
    original_sale_id BIGINT REFERENCES sale(id),
    customer_id BIGINT REFERENCES customer(id),
    return_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_refund_amount NUMERIC(12, 2) NOT NULL,
    refund_type VARCHAR(30) NOT NULL, -- 'CASH_REFUND' or 'DUE_ADJUSTMENT'
    reason TEXT
);

-- 10. Sale Return Items (With Damaged Goods Routing)
CREATE TABLE sale_return_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_return_id BIGINT NOT NULL REFERENCES sale_return(id) ON DELETE CASCADE,
    lot_id BIGINT NOT NULL REFERENCES inventory_lot(id),
    quantity NUMERIC(12, 3) NOT NULL,
    refund_price NUMERIC(12, 2) NOT NULL,
    is_damaged BOOLEAN DEFAULT FALSE,
    restock_location VARCHAR(20) NOT NULL -- 'DOKAN' or 'GODOWN'
);

-- Performance & Lookup Indexes
CREATE INDEX idx_inventory_lot_product ON inventory_lot(product_id);
CREATE INDEX idx_inventory_lot_expiry ON inventory_lot(expiry_date);
CREATE INDEX idx_stock_inventory_lot ON stock_inventory(lot_id);
CREATE INDEX idx_godown_movement_lot ON godown_movement(lot_id);
CREATE INDEX idx_customer_phone ON customer(phone);
CREATE INDEX idx_customer_ledger_customer ON customer_ledger(customer_id);
CREATE INDEX idx_customer_ledger_sale ON customer_ledger(sale_id);
CREATE INDEX idx_sale_customer ON sale(customer_id);
CREATE INDEX idx_sale_invoice ON sale(invoice_no);
CREATE INDEX idx_sale_date ON sale(sale_date);
CREATE INDEX idx_sale_item_sale ON sale_item(sale_id);
CREATE INDEX idx_sale_item_lot ON sale_item(lot_id);
CREATE INDEX idx_sale_return_sale ON sale_return(original_sale_id);
CREATE INDEX idx_sale_return_customer ON sale_return(customer_id);
CREATE INDEX idx_sale_return_item_return ON sale_return_item(sale_return_id);
CREATE INDEX idx_sale_return_item_lot ON sale_return_item(lot_id);
