-- ============================================================================
-- V2__stock_ledger_and_adjustments.sql
-- Immutable Stock Movement Ledger (Bin Card) & Stock Adjustments
-- ============================================================================

-- 1. Immutable Stock Movement Ledger (Bin Card)
CREATE TABLE stock_movement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    lot_id BIGINT NOT NULL REFERENCES inventory_lot(id) ON DELETE CASCADE,
    movement_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    movement_type VARCHAR(40) NOT NULL,
    location VARCHAR(20) NOT NULL DEFAULT 'DOKAN',
    quantity_change NUMERIC(12, 3) NOT NULL,
    balance_before NUMERIC(12, 3) NOT NULL,
    balance_after NUMERIC(12, 3) NOT NULL,
    unit VARCHAR(30) NOT NULL,
    reference_doc_no VARCHAR(100),
    remarks VARCHAR(255),
    performed_by VARCHAR(100)
);

CREATE INDEX idx_stock_movement_lot ON stock_movement(lot_id);
CREATE INDEX idx_stock_movement_product ON stock_movement(product_id);
CREATE INDEX idx_stock_movement_time ON stock_movement(movement_time DESC);
CREATE INDEX idx_stock_movement_type ON stock_movement(movement_type);

-- 2. Stock Adjustment (Shrinkage, Damage, Breakage & Physical Variance)
CREATE TABLE stock_adjustment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adjustment_no VARCHAR(50) NOT NULL UNIQUE,
    adjustment_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    product_id BIGINT NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    lot_id BIGINT NOT NULL REFERENCES inventory_lot(id) ON DELETE CASCADE,
    adjustment_type VARCHAR(40) NOT NULL,
    quantity NUMERIC(12, 3) NOT NULL,
    unit VARCHAR(30) NOT NULL,
    action_type VARCHAR(30) NOT NULL,
    cost_price NUMERIC(12, 2) NOT NULL,
    total_loss_value NUMERIC(12, 2) NOT NULL,
    reason TEXT NOT NULL,
    performed_by VARCHAR(100)
);

CREATE SEQUENCE adjustment_number_seq START WITH 1001 INCREMENT BY 1;
CREATE INDEX idx_stock_adjustment_lot ON stock_adjustment(lot_id);
CREATE INDEX idx_stock_adjustment_product ON stock_adjustment(product_id);
CREATE INDEX idx_stock_adjustment_date ON stock_adjustment(adjustment_date DESC);

-- 3. Seed opening balance entries for existing baseline inventory
INSERT INTO stock_movement (
    product_id, lot_id, movement_time, movement_type, location,
    quantity_change, balance_before, balance_after, unit,
    reference_doc_no, remarks, performed_by
)
SELECT 
    l.product_id, 
    s.lot_id, 
    COALESCE(l.created_at, CURRENT_TIMESTAMP), 
    'OPENING_BALANCE', 
    s.location, 
    s.quantity, 
    0.000, 
    s.quantity, 
    p.base_unit, 
    'INIT-MIGRATION', 
    'Initial opening stock baseline', 
    'System'
FROM stock_inventory s
JOIN inventory_lot l ON s.lot_id = l.id
JOIN product p ON l.product_id = p.id
WHERE s.quantity > 0;
