-- ============================================================================
-- V5__add_users.sql
-- Al-Amin POS & Inventory Management System - Staff Login Accounts
--
-- Compatibility: PostgreSQL 10+
-- Adds a dedicated app_user table so staff log in with a username and
-- password (JWT-issued) rather than relying only on the anonymous cashier
-- session and shared 4-digit Owner PIN.
-- ============================================================================

CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT DEFAULT 0 NOT NULL,
    username VARCHAR(60) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    full_name VARCHAR(150),
    role VARCHAR(30) NOT NULL,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMP,
    CONSTRAINT uq_app_user_username UNIQUE (username)
);

-- Seed default accounts.
-- IMPORTANT: change these passwords after first login in a production deployment.
--   owner   / owner123    (ROLE_OWNER)
--   cashier / cashier123  (ROLE_CASHIER)
INSERT INTO app_user (username, password_hash, full_name, role, active)
VALUES
    ('owner', '$2b$10$ZX1S0b8lqGKqdqa7Vd8iq.AQJ.BfPpp/DQMu7nezZMWnTDYajvZ.W', 'Shop Owner', 'ROLE_OWNER', TRUE),
    ('cashier', '$2b$10$TPclmyFyJNkjmRY0pL3TGuirUhjsFaNF3r1lQOKxT0sF4g38k7/9i', 'Counter Cashier', 'ROLE_CASHIER', TRUE)
ON CONFLICT (username) DO NOTHING;
