"""initial_schema

Revision ID: 1553d6061019
Revises: 
Create Date: 2026-09-26 21:35:52.321323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1553d6061019'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('father_name', sa.String(length=150), nullable=True),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('whatsapp_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('village_address', sa.String(length=255), nullable=True),
    sa.Column('land_area', sa.String(length=100), nullable=True),
    sa.Column('customer_type', sa.String(length=30), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_purchases', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mfs_type', sa.String(length=30), nullable=True),
    sa.Column('mfs_number', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_branch', sa.String(length=100), nullable=True),
    sa.Column('bank_account_no', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_phone'), ['phone'], unique=False)

    op.create_table('document_sequences',
    sa.Column('sequence_name', sa.String(length=64), nullable=False),
    sa.Column('current_val', sa.BigInteger(), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('max_val', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sequence_name')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_bn', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('base_unit', sa.String(length=30), nullable=False),
    sa.Column('carton_multiplier', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('default_barcode', sa.String(length=100), nullable=True),
    sa.Column('standard_retail_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('standard_wholesale_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('buying_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('min_stock_alert', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code')
    )
    op.create_table('customer_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('debit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('money_receipt_no', sa.String(length=50), nullable=True),
    sa.Column('sale_id', sa.BigInteger(), nullable=True),
    sa.Column('client_trx_id', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_ledger_client_trx_id'), ['client_trx_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_customer_ledger_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_ledger_transaction_date'), ['transaction_date'], unique=False)

    op.create_table('inventory_lot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_number', sa.String(length=50), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('purchase_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lot_retail_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lot_wholesale_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=False),
    sa.Column('supplier_name', sa.String(length=150), nullable=True),
    sa.Column('challan_no', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_lot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_lot_barcode'), ['barcode'], unique=True)
        batch_op.create_index(batch_op.f('ix_inventory_lot_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_lot_product_id'), ['product_id'], unique=False)

    op.create_table('sale',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('sale_date', sa.DateTime(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('sale_mode', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('round_off', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('cash_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cash_tendered', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('change_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('digital_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('digital_medium', sa.String(length=30), nullable=True),
    sa.Column('digital_trx_id', sa.String(length=100), nullable=True),
    sa.Column('due_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cashier_name', sa.String(length=100), nullable=True),
    sa.Column('client_trx_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_client_trx_id'), ['client_trx_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_sale_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_invoice_no'), ['invoice_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_sale_sale_date'), ['sale_date'], unique=False)

    op.create_table('sale_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('total_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['inventory_lot.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_item_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_item_sale_id'), ['sale_id'], unique=False)

    op.create_table('sale_return',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('return_no', sa.String(length=50), nullable=False),
    sa.Column('original_sale_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=False),
    sa.Column('total_refund_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('refund_type', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('client_trx_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['original_sale_id'], ['sale.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_return', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_return_client_trx_id'), ['client_trx_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_sale_return_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_return_return_date'), ['return_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_return_return_no'), ['return_no'], unique=True)

    op.create_table('stock_adjustment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('adjustment_no', sa.String(length=50), nullable=False),
    sa.Column('adjustment_date', sa.DateTime(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('adjustment_type', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_loss_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('performed_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['inventory_lot.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_adjustment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_adjustment_adjustment_date'), ['adjustment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_adjustment_adjustment_no'), ['adjustment_no'], unique=True)

    op.create_table('stock_inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['inventory_lot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_id', 'location', name='uq_lot_location')
    )
    with op.batch_alter_table('stock_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_inventory_lot_id'), ['lot_id'], unique=False)

    op.create_table('stock_movement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('movement_time', sa.DateTime(), nullable=False),
    sa.Column('movement_type', sa.String(length=40), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=False),
    sa.Column('quantity_change', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('reference_doc_no', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('performed_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['inventory_lot.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_movement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movement_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movement_movement_time'), ['movement_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movement_product_id'), ['product_id'], unique=False)

    op.create_table('sale_return_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sale_return_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('refund_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_damaged', sa.Boolean(), nullable=False),
    sa.Column('restock_location', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['inventory_lot.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_return_id'], ['sale_return.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_return_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_return_item_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_return_item_sale_return_id'), ['sale_return_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_return_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_return_item_sale_return_id'))
        batch_op.drop_index(batch_op.f('ix_sale_return_item_lot_id'))

    op.drop_table('sale_return_item')
    with op.batch_alter_table('stock_movement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movement_product_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movement_movement_time'))
        batch_op.drop_index(batch_op.f('ix_stock_movement_lot_id'))

    op.drop_table('stock_movement')
    with op.batch_alter_table('stock_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_inventory_lot_id'))

    op.drop_table('stock_inventory')
    with op.batch_alter_table('stock_adjustment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_adjustment_adjustment_no'))
        batch_op.drop_index(batch_op.f('ix_stock_adjustment_adjustment_date'))

    op.drop_table('stock_adjustment')
    with op.batch_alter_table('sale_return', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_return_return_no'))
        batch_op.drop_index(batch_op.f('ix_sale_return_return_date'))
        batch_op.drop_index(batch_op.f('ix_sale_return_customer_id'))
        batch_op.drop_index(batch_op.f('ix_sale_return_client_trx_id'))

    op.drop_table('sale_return')
    with op.batch_alter_table('sale_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_item_sale_id'))
        batch_op.drop_index(batch_op.f('ix_sale_item_lot_id'))

    op.drop_table('sale_item')
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_sale_date'))
        batch_op.drop_index(batch_op.f('ix_sale_invoice_no'))
        batch_op.drop_index(batch_op.f('ix_sale_customer_id'))
        batch_op.drop_index(batch_op.f('ix_sale_client_trx_id'))

    op.drop_table('sale')
    with op.batch_alter_table('inventory_lot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_lot_product_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_lot_expiry_date'))
        batch_op.drop_index(batch_op.f('ix_inventory_lot_barcode'))

    op.drop_table('inventory_lot')
    with op.batch_alter_table('customer_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_ledger_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_customer_ledger_customer_id'))
        batch_op.drop_index(batch_op.f('ix_customer_ledger_client_trx_id'))

    op.drop_table('customer_ledger')
    op.drop_table('product')
    op.drop_table('document_sequences')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_phone'))

    op.drop_table('customer')
    op.drop_table('app_user')
    # ### end Alembic commands ###
