"""add_pack_size_and_carton_prices_to_product

Revision ID: d7b69b03676b
Revises: 1553d6061019
Create Date: 2026-10-02 15:24:55.589316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7b69b03676b'
down_revision: Union[str, Sequence[str], None] = '1553d6061019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_lot', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pack_size', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('unit_size', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('carton_wholesale_price', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('carton_buying_price', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('carton_buying_price')
        batch_op.drop_column('carton_wholesale_price')
        batch_op.drop_column('unit_size')
        batch_op.drop_column('pack_size')

    with op.batch_alter_table('inventory_lot', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    # ### end Alembic commands ###
